<?php
define('SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE', 'http://interface.hzjd0572.com/Wechat');
return array(
    'WECHAT_PLATFORM_REPLY_AUTOMATIC_DEFAULT'=>'首页',
    'WECHAT_PLATFORM_REPLY_SUBSCRIBE_DEFAULT'=>'首页',
    'WECHAT_PLATFORM_FANS_SYNC'=>'',
    'WECHAT_PLATFORM_FANS_SYNC_DETAIL'=>'',
    
    'INTERFACE_WECHAT_PLATFORM_MENU_ADDS'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformMenu/adds',
    'INTERFACE_WECHAT_PLATFORM_MENU_DELE'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformMenu/dele',
    'INTERFACE_WECHAT_PLATFORM_FANS_GROUP_ADDS'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformFansGroup/adds',
    'INTERFACE_WECHAT_PLATFORM_FANS_GROUP_EDIT'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformFansGroup/edit',
    'INTERFACE_WECHAT_PLATFORM_FANS_GROUP_GET_RESULTS'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformFansGroup/getResults',
    'INTERFACE_WECHAT_PLATFORM_FANS_LISTS'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformFans/getResults',
    'INTERFACE_WECHAT_PLATFORM_FANS_DETAIL'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformFans/getDetail',
    'INTERFACE_QR_CODE_TICKET'=>SITE_URL_INTERFACE_WECHAT_PLATFORM_MODULE.'/WechatPlatformQrCode/getTicket',
);